### ISSUE TITLE
Agenda 10/10/23 

### ISSUE THREAD

**Issue by cjj01** [aaronr7734/team-8-project#13]
[Agenda 10_5_23.pdf](https://github.com/aaronr7734/team-8-project/files/12850888/Agenda.10_5_23.pdf)
Write the issues that we need to talk about at the next meeting.

**Comment by plii32** [comment]
I think the main developer role is unnecessary. I think that the manager could include splitting work.

**Comment by cmb2333** [comment]
We should write the agenda in github rather than downloading it.

**Comment by JEN5812** [comment]
We should look over the roles and try to balance them out between people. I think we need to add the action of someone else officially looking over deliverables and reports before submitting besides one person.
